server:
  port: 8060

spring:
  cloud:
    gateway:
      routes:
        - id: artwork-service
          uri: lb://artwork-service
          predicates:
            - Path=/artist/**,/artwork/**,/genre/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
