server:
  port: 8070

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  data:
    mongodb:
      uri: mongodb+srv://josue:REDACTED@localhost:27017/pictorial-arcane?retryWrites=true&w=majority
      database: pictorial-arcane

