spring.application.name=audit-service

# Configuración de Spring Data Cassandra para Astra DB
spring.cassandra.keyspace-name=pictorial_arcane
spring.cassandra.username=token
spring.cassandra.password=REDACTED
spring.cassandra.schema-action=none

# Tiempos de espera (Timeouts)
spring.cassandra.request.timeout=10s
spring.cassandra.connection.connect-timeout=10s
spring.cassandra.connection.init-query-timeout=10s

# Ruta al archivo Secure Connect Bundle (SCB)
astra.secure-connect-bundle=classpath:secure-connect-pictorial-db.zip

spring.config.import=optional:configserver:http://localhost:8088

server.port=8071

#Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
