spring.application.name=audit-service

# Configuracion de Spring Data Cassandra para Astra DB
spring.cassandra.keyspace-name=${CASSANDRA_KEYSPACE:pictorial_arcane}
spring.cassandra.username=${CASSANDRA_USERNAME:token}
spring.cassandra.password=${CASSANDRA_PASSWORD:}
spring.cassandra.schema-action=none

# Tiempos de espera (Timeouts)
spring.cassandra.request.timeout=10s
spring.cassandra.connection.connect-timeout=10s
spring.cassandra.connection.init-query-timeout=10s

# Ruta al archivo Secure Connect Bundle (SCB)
astra.secure-connect-bundle=${ASTRA_SECURE_CONNECT_BUNDLE:classpath:secure-connect-pictorial-db.zip}

spring.config.import=optional:configserver:http://localhost:8088

server.port=8071
springdoc.api-docs.path=/artwork-status-history/v3/api-docs

#Eureka
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

