spring.application.name=artwork-service
spring.config.import=optional:configserver:http://localhost:8088

server.port=8070

#Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Configuración de MongoDB en la nube (Reemplaza con tus credenciales reales)
spring.data.mongodb.uri=mongodb+srv://josue:REDACTED@localhost:27017/pictorial-arcane?retryWrites=true&w=majority
spring.data.mongodb.database=pictorial-arcane

# Ver las operaciones de Spring Data MongoDB
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
# Ver la conectividad del driver de Mongo (handshake, clusters, etc.)
logging.level.org.mongodb.driver.cluster=DEBUG




