spring.application.name=recommendation-service
spring.config.import=optional:configserver:http://localhost:8088

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Neo4J
spring.neo4j.uri=neo4j+s://localhost:7687

# Credenciales de acceso
spring.neo4j.authentication.username=53ca7660
spring.neo4j.authentication.password=REDACTED
spring.data.neo4j.database=53ca7660
spring.data.neo4j.initial-index-creation=none

# Muestra la inicialización del driver, creación de canales (sockets) y el handshake con la BD
logging.level.org.neo4j.driver=DEBUG

# Muestra cómo Spring Data gestiona las sesiones y las consultas Cypher que se ejecutan
logging.level.org.springframework.data.neo4j=DEBUG