spring.application.name=core-service

spring.config.import=optional:configserver:
spring.cloud.config.uri=http://localhost:8088

server.port=8082

#Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

#Postgres SQL
spring.datasource.driver-class-name=org.postgresql.Driver

#Spring Data JPA
spring.datasource.url=${DB_URL:jdbc:postgresql://pictorial-db.postgres.database.azure.com:5432/pictorial_arcane_db?sslmode=require}
spring.datasource.username=${DB_USER:uneg}
spring.datasource.password=${DB_PASSWORD:REDACTED}

spring.jpa.hibernate.ddl-auto=${HIBERNATE_MODE:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

#Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=user@example.com
spring.mail.password=${GMAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.docker.compose.enabled=${DOCKER_CONF:false}
